name: haystack
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2025.1.31=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - conda-pack=0.7.1=py312h06a4308_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - eigen=3.4.0=hdb19cb5_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py312h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=4.3.0=hf52aaf7_2
  - hdf5=1.12.1=h2b7332f_3
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py312h06a4308_1
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.7.77=0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.0=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.9.2=py312h06a4308_1
  - matplotlib-base=3.9.2=py312hbfdbfaf_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mpmath=1.3.0=py312h06a4308_0
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py312h06a4308_0
  - numexpr=2.10.1=py312h3c60e43_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - opencv=4.10.0=py312h907dce5_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.1=py312h06a4308_0
  - pandas=2.2.3=py312h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pip=24.2=py312h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - ply=3.11=py312h06a4308_1
  - pyparsing=3.2.0=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.7=h5148396_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.5.1=py3.12_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - qt-main=5.15.2=hb6262e9_11
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - scipy=1.14.1=py312hc5e2394_0
  - setuptools=72.1.0=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.5.1=py312_cu121
  - torchtriton=3.1.0=py312
  - torchvision=0.20.1=py312_cu121
  - tornado=6.4.1=py312h5eee18b_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.3=py312h06a4308_0
  - wheel=0.44.0=py312h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==0.26.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - albucore==0.0.23
      - albumentations==1.4.24
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.7.0
      - attrs==25.1.0
      - av==14.2.0
      - bitsandbytes==0.45.2
      - blis==1.3.0
      - braceexpand==0.1.7
      - catalogue==2.0.10
      - click==8.1.8
      - cloudpathlib==0.21.0
      - confection==0.1.5
      - cymem==2.0.11
      - cython==3.0.11
      - datasets==3.2.0
      - decord==0.6.0
      - deepspeed==0.14.4
      - defusedxml==0.7.1
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - fastapi==0.115.6
      - ffmpeg-python==0.2.0
      - ffmpy==0.5.0
      - fire==0.4.0
      - flash-attn==2.7.4.post1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.16.0
      - gradio-client==0.8.1
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.27.0
      - imageio==2.36.1
      - importlib-resources==6.5.2
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - langcodes==3.5.0
      - language-data==1.3.0
      - latex2mathml==3.77.0
      - lazy-loader==0.4
      - lightning-utilities==0.13.1
      - llava==1.2.2.post1
      - lvis==0.5.3
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markdown2==2.5.3
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.6
      - mmyolo==0.6.0
      - modelscope==1.23.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.12
      - narwhals==1.27.1
      - ninja==1.11.1.3
      - nltk==3.9.1
      - nvidia-ml-py==12.570.86
      - nvitop==1.4.2
      - openai==1.59.3
      - orjson==3.10.13
      - peft==0.14.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - preshed==3.0.9
      - prettytable==3.12.0
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==6.1.0
      - ptflops==0.7.4
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.0
      - pycocotools==2.0.8
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.18.0
      - pynvml==12.0.0
      - python-multipart==0.0.20
      - qwen-vl-utils==0.0.10
      - referencing==0.36.2
      - regex==2024.11.6
      - rich==13.9.4
      - rpds-py==0.22.3
      - ruff==0.8.5
      - safehttpx==0.1.6
      - safetensors==0.5.0
      - scikit-image==0.25.2
      - scikit-learn==1.2.2
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==4.0.2
      - sentencepiece==0.1.99
      - sentry-sdk==2.22.0
      - setproctitle==1.3.4
      - shapely==2.0.6
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - simsimd==6.2.1
      - smart-open==7.1.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - socksio==1.0.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - starlette==0.41.3
      - stringzilla==3.11.3
      - supervision==0.25.1
      - svgwrite==1.4.3
      - sympy==1.13.1
      - termcolor==2.5.0
      - terminaltables==3.1.10
      - thinc==8.3.6
      - threadpoolctl==3.5.0
      - tifffile==2025.2.18
      - timm==1.0.14
      - tokenizers==0.21.0
      - tomlkit==0.12.0
      - torchmetrics==1.6.2
      - tqdm==4.67.1
      - transformers==4.49.0
      - typer==0.15.1
      - ultralytics==8.3.40
      - ultralytics-thop==2.0.12
      - uvicorn==0.34.0
      - video2dataset==1.0.0
      - wandb==0.19.6
      - wasabi==1.1.3
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webdataset==0.2.111
      - websockets==11.0.3
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.18.3
      - yt-dlp==2025.2.19
prefix: /data/guoweiyu/anaconda3/envs/haystack
